name: home-media-server

networks:
  media-network:
    ipam:
      config:
        - subnet: 172.10.0.0/24

services:
  # Wireguard Peer
  WGClientNode:
    image: ghcr.io/digitallyrefined/docker-wireguard-tunnel:v3
    container_name: wg-peer1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      # Note that DOMAIN & PEERS are not required for the peer
      # Services to expose format (comma-separated)
      # SERVICES=peer-id:peer-container-name:peer-container-port:expose-port-as
      - SERVICES=peer1:jellyfin:8096:8096,peer1:homarr:7575:7575,peer1:audiobookshelf:80:8196,peer1:kavita:5000:5112
    cap_add:
      - NET_ADMIN
    volumes:
      - ${APPDATA_PATH}/wg_peer1:/etc/wireguard
    restart: unless-stopped
    links:
      - Jellyfin:jellyfin
      - Homarr:homarr
      - Audiobookshelf:audiobookshelf
      - Kavita:kavita
    networks:
      media-network:
  Homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${APPDATA_PATH}/homarr/configs:/app/data/configs
      - ${APPDATA_PATH}/homarr/icons:/app/public/icons
      - ${APPDATA_PATH}/homarr/data:/data
    ports:
      - '7575:7575'
    networks:
      media-network:
        ipv4_address: 172.10.0.4
  # Jellyfin
  Jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/jellyfin:/config
      - ${MEDIA_PATH}/storage/media:/media
    ports:
      - 8096:8096
    group_add:
      - "109"
    networks:
      media-network:
        ipv4_address: 172.10.0.3
  Audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - ${APPDATA_PATH}/audiobookshelf/config:/config
      - ${APPDATA_PATH}/audiobookshelf/metadata>:/metadata
      - ${MEDIA_PATH}/storage/media/books/audiobooks:/audiobooks
    environment:
      - TZ=Asia/Kolkata
    networks:
      media-network:
        ipv4_address: 172.10.0.5
  Kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/kavita:/config
      - ${MEDIA_PATH}/storage:/storage
    ports:
      - 5112:5000
    restart: unless-stopped
    networks:
      media-network:
        ipv4_address: 172.10.0.6
  #VPN
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - ${APPDATA_PATH}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
    networks:
      media-network:
    ports:
      # Lazylibrary
      - 5299:5299
      # Whisparr
      - 6969:6969
      # Readarr
      - 8787:8787
      # Lidarr
      - 8686:8686
      # Bazarr
      - 6767:6767
      # Jellyser
      - 5055:5055
      # Sonarr
      - 8989:8989
      # Radarr
      - 7878:7878
      # Flaresolver
      - 8191:8191
      # Prowlarr
      - 9696:9696
      # Qbit
      - 8091:8091
      - 6881:6881
      - 6881:6881/udp
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/readarr:/config
      - ${MEDIA_PATH}/storage:/storage
  Bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/bazarr:/config
      - ${MEDIA_PATH}/storage:/storage
    network_mode: "service:gluetun"
    restart: unless-stopped
  Jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
        - LOG_LEVEL=debug
        - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/jellyseerr:/app/config
    restart: unless-stopped
    depends_on:
      - Sonarr
      - Radarr
    network_mode: "service:gluetun"
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - ${APPDATA_PATH}/lazylibrarian:/config
      - ${MEDIA_PATH}/storage:/storage
    network_mode: "service:gluetun"
    restart: unless-stopped
  Lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    depends_on:
      - Prowlarr
    volumes:
      - ${APPDATA_PATH}/lidarr:/config
      - ${MEDIA_PATH}/storage:/storage
    network_mode: "service:gluetun"
  Sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/sonarr:/config
      - ${MEDIA_PATH}/storage:/storage
    depends_on:
      - Prowlarr
    network_mode: "service:gluetun"
  Radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/radarr:/config
      - ${MEDIA_PATH}/storage:/storage
    depends_on:
      - Prowlarr
    network_mode: "service:gluetun"
  Prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Kolkata
    volumes:
      - ${APPDATA_PATH}/prowlarr:/config
    network_mode: "service:gluetun"
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Kolkata
    restart: unless-stopped
    network_mode: "service:gluetun"
  # Torrent - Qbit
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8091
      - TORRENTING_PORT=6881
    volumes:
      - ${APPDATA_PATH}/qbittorrent/:/config
      - ${MEDIA_PATH}/storage/:/storage
    network_mode: "service:gluetun"
    restart: unless-stopped
